import Package.TaxiCar;
import Package.Tiger;
import Package.FullTimeEmployee;
import Package.PartTimeEmployee;
import Package.OfflineStudent;
import Package.OnlineStudent;
import Package.Customer;
import Package.VIPCustomer;
public class App {
    public static void main(String[] args) throws Exception {
        OfflineStudent offS = new OfflineStudent();
        OnlineStudent onS = new OnlineStudent();
        FullTimeEmployee ftEmp = new FullTimeEmployee();
        PartTimeEmployee ptEmp = new PartTimeEmployee();
        Customer ctm = new Customer();
        VIPCustomer vipCtm = new VIPCustomer();
        Tiger tiger = new Tiger();
        TaxiCar taxi = new TaxiCar();
    System.out.println("-----OfflineStudent-----");
        offS.addName();
        offS.addStudentID();   
        offS.addClassTime();
        offS.displayName();
        offS.displayStudentID();
        offS.displayClassTime();
        offS.placeToStudy();
    System.out.println("-----OnlineStudent-----");
        onS.addName();
        onS.addStudentID();   
        onS.addTimeOut();
        onS.displayName();
        onS.displayStudentID();
        onS.displayTimeOut();
        onS.placeToStudy();
    System.out.println("-----FullTimeEmployee-----");
        ftEmp.addName();
        ftEmp.addOvertimeHours();
        ftEmp.displayName();
        ftEmp.displayPosition();
    System.out.println("Luong: " + ftEmp.Salary());
        ftEmp.typeOfEmployee();
    System.out.println("-----PartTimeEmployee-----");
        ptEmp.addName();
        ptEmp.addNumberOfDayWork();
        ptEmp.displayName();
        ptEmp.displayPosition();
    System.out.println("Luong: " + ptEmp.Salary());
        ptEmp.typeOfEmployee();
    System.out.println("-----Customer-----");
        ctm.addName();
        ctm.addCustomerID();
        ctm.displayName();
        ctm.displayCustomerID();
    System.out.println("-----VIPCustomer-----");
        vipCtm.addName();
        vipCtm.addCustomerID();
        vipCtm.displayName();
        vipCtm.displayCustomerID();
        vipCtm.Gifts();
    System.out.println("-----Animal-----");
        tiger.Eat();
        tiger.Sleep();
        tiger.Walk();
        tiger.Run();
        tiger.Roar();
    System.out.println("-----Car-----");
        taxi.Move();
        taxi.Stop();
        taxi.TurnRight();
        taxi.TurnLeft();
        taxi.Reverse();  
    }
}